-- Recallix AI — the ORIGINAL schema, as of V1__init.sql.
--
-- NOT the current one, and not a source of truth. Flyway owns the schema; the
-- migrations under backend-spring/src/main/resources/db/migration are what runs,
-- and this file is kept only as a readable starting point. Twenty-four
-- migrations have landed since, several of them destructive. Read the
-- migrations, or `\d` a live database, before trusting anything below.
--
-- Where this file is now WRONG:
--   * meetings.participants — dropped (V23). Recallix never joins a meeting, so
--     it never learns who attended; the column only held what an uploader typed.
--   * meeting_decisions, meeting_risks — dropped (V14), along with decision
--     drift. Replaced in V24 by meeting_insights, which reads decisions and
--     risks out of the summary sections instead of extracting them separately.
--   * agent_connections, agent_action_requests, external_sync_logs — the agent
--     and Meeting Memory features were removed (V15), and the calendar and
--     integrations that used them in V18/V19.
--   * meeting_summaries — has gained sections_json, quotes_json, template_slug
--     and stale since (V12, V22, V25).
--   * transcript_segments — has gained words_json (V13) and language (V21).
--   * Row-level security (V9/V11) is not shown here at all, and it is not
--     optional: every user-owned table carries a FORCE'd tenant_isolation
--     policy, and the app connects as a NOBYPASSRLS role.
--
-- IDs are text (prefixed: usr_, mtg_, ai_, ins_, sub_, aud_) generated by the app.

CREATE TABLE IF NOT EXISTS users (
    id              TEXT PRIMARY KEY,
    clerk_user_id   TEXT UNIQUE NOT NULL,
    email           TEXT,
    plan            TEXT NOT NULL DEFAULT 'FREE',   -- FREE | PRO | PREMIUM
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS meetings (
    id               TEXT PRIMARY KEY,
    user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title            TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'CREATED', -- see api-contracts §5
    audio_url        TEXT,
    object_key       TEXT,
    duration_seconds INTEGER,
    participants     JSONB DEFAULT '[]',
    tags             JSONB DEFAULT '[]',
    error_message    TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_meetings_user ON meetings(user_id);
CREATE INDEX IF NOT EXISTS idx_meetings_status ON meetings(status);

CREATE TABLE IF NOT EXISTS meeting_transcripts (
    id            TEXT PRIMARY KEY,
    meeting_id    TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    transcript_text TEXT NOT NULL,
    language      TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_transcripts_meeting ON meeting_transcripts(meeting_id);

CREATE TABLE IF NOT EXISTS transcript_segments (
    id          TEXT PRIMARY KEY,
    meeting_id  TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    start_time  DOUBLE PRECISION,
    end_time    DOUBLE PRECISION,
    speaker     TEXT,
    text        TEXT
);
CREATE INDEX IF NOT EXISTS idx_segments_meeting ON transcript_segments(meeting_id);

CREATE TABLE IF NOT EXISTS meeting_summaries (
    id               TEXT PRIMARY KEY,
    meeting_id       TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    short_summary    TEXT,
    detailed_summary TEXT,
    key_points_json  JSONB DEFAULT '[]',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_summaries_meeting ON meeting_summaries(meeting_id);

CREATE TABLE IF NOT EXISTS meeting_decisions (
    id              TEXT PRIMARY KEY,
    meeting_id      TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    decision_text   TEXT NOT NULL,
    source_sentence TEXT,
    confidence      TEXT
);
CREATE INDEX IF NOT EXISTS idx_decisions_meeting ON meeting_decisions(meeting_id);

CREATE TABLE IF NOT EXISTS meeting_action_items (
    id              TEXT PRIMARY KEY,
    meeting_id      TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    owner_name      TEXT,
    due_date        TEXT,
    priority        TEXT DEFAULT 'medium',           -- high | medium | low
    status          TEXT NOT NULL DEFAULT 'OPEN',     -- OPEN | IN_PROGRESS | DONE
    source_sentence TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_actions_meeting ON meeting_action_items(meeting_id);
CREATE INDEX IF NOT EXISTS idx_actions_status ON meeting_action_items(status);

CREATE TABLE IF NOT EXISTS meeting_risks (
    id              TEXT PRIMARY KEY,
    meeting_id      TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    risk_text       TEXT NOT NULL,
    severity        TEXT DEFAULT 'medium',
    source_sentence TEXT
);
CREATE INDEX IF NOT EXISTS idx_risks_meeting ON meeting_risks(meeting_id);

CREATE TABLE IF NOT EXISTS usage_limits (
    id             TEXT PRIMARY KEY,
    user_id        TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    period_start   TIMESTAMPTZ NOT NULL,
    period_end     TIMESTAMPTZ NOT NULL,
    meetings_used  INTEGER NOT NULL DEFAULT 0,
    ai_minutes_used INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_usage_user ON usage_limits(user_id);

CREATE TABLE IF NOT EXISTS subscriptions (
    id                     TEXT PRIMARY KEY,
    user_id                TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    stripe_customer_id     TEXT,
    stripe_subscription_id TEXT,
    status                 TEXT,
    plan                   TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id          TEXT PRIMARY KEY,
    user_id     TEXT,
    action      TEXT NOT NULL,
    entity_type TEXT,
    entity_id   TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);

-- Transactional outbox for reliable DB->Kafka publishing (Outbox Pattern).
CREATE TABLE IF NOT EXISTS outbox_events (
    id           TEXT PRIMARY KEY,
    topic        TEXT NOT NULL,
    partition_key TEXT,
    payload      JSONB NOT NULL,
    published    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox_events(published) WHERE published = FALSE;

-- ---- Phase 2: Agent + MCP (scaffolded) ----
CREATE TABLE IF NOT EXISTS agent_connections (
    id            TEXT PRIMARY KEY,
    user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider      TEXT NOT NULL,          -- notion | gmail | google_calendar | outlook_mail | outlook_calendar | microsoft_tasks
    account_email TEXT,
    scopes_json   JSONB DEFAULT '[]',
    status        TEXT NOT NULL DEFAULT 'DISCONNECTED',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_action_requests (
    id                TEXT PRIMARY KEY,
    user_id           TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    meeting_id        TEXT REFERENCES meetings(id) ON DELETE CASCADE,
    action_type       TEXT NOT NULL,      -- CREATE_NOTION_NOTE | DRAFT_EMAIL | SEND_EMAIL | CREATE_CALENDAR_EVENT | CREATE_TASKS ...
    provider          TEXT,
    draft_payload_json JSONB NOT NULL,
    status            TEXT NOT NULL DEFAULT 'DRAFT',  -- DRAFT | APPROVED | EXECUTED | FAILED | REJECTED
    approval_required BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    executed_at       TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS external_sync_logs (
    id                 TEXT PRIMARY KEY,
    user_id            TEXT,
    provider           TEXT,
    external_entity_id TEXT,
    action_request_id  TEXT,
    status             TEXT,
    error_message      TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
